app.config(function ($translateProvider) {
    $translateProvider.translations('en', {
        Logintext: 'Login',
        Signuptext: 'Sign Up',
        Logindescription: 'If you have email and password, you can use the button below to access the secured content using a token',
        Registrationdescription: 'Use the button below to create Email and Password to access the secured content using a token',
        Email: 'Email',
        Password: 'Password',
        Rememberme: 'Remember me',
        Forgotpassword: 'Forgot Password',
        Register: 'Register',
        Pleasewait: 'Please wait',
        Firstname: 'First Name',
        Lastname: 'Last Name',
        Confirmpassword: 'Confirm Password',
        Submit: 'Submit',
        Forgotheading: 'Type your email-address to retrieve your Password',
        Getpassword: 'Get Password',
        Menu: 'Menu',
        Hello: 'Hello',
        Utilisationtoday: 'Utilisation today',
        Currentutilisation: 'Current utilisation',
        Youhaveused: 'you have used',
        Sofartoday: 'since Midnight',
        Wholehouse: 'Whole house',
        Avgweekdayutilisation: 'Average weekday utilisation',
        Expectedutilisationtoday: 'Expected utilisation today',
        Setting: 'Setting',
        Signout: 'Sign Out',
        Last24hrs: 'Last 24hrs',
        Last7days: 'Last 7days',
        Lastmonth: 'Last month',
        Last6month: 'Last 6 month',
        Lastyear: 'Last Year',
        EqualmessageText: 'Average day utilisation and expected day utilisation are Equal',
        lessmessageText: 'Average day utilisation is less than expected day utilisation',
        greatermessageText: 'Average day utilisation is greater than expected day utilisation',
        russiantext: 'Russian',
        spanishtext: 'Spanish',
        home: 'Home',
        household: 'House hold',
        kWh: 'kWh',
        browserdetails: 'Browser details',
        alerts: 'Alerts',
        householdprofile: 'Household profile',
        tariff: 'Tariff',
        setup: 'Setup',
        propertytype: 'Property type',
        numberofadults: 'Number of Adults',
        numberofchildren: 'Number of Children',
        numberofbedroom: 'Number of Bedroom',
        electricityprovider: 'Electricity provider',
        alertconfiguration: 'Alert configuration',
        highUsagehour: 'High usage - Hour',
        highusageday: 'High usage - Day',
        appliancelefton: 'Appliance left on',
        largeconsumes: 'Large consumes (e.g. Oven, Heater)',
        computers: 'Computers, TV, games, Consoles, etc',
        lights: 'Lights',
        emaildestination: 'Email Destination',
        cancel: 'cancel',
        comparisonview: 'Comparison view',
        type: 'Type',
        resident: 'Resident ',
        adults: 'Adults',
        region: 'Region',
        startdate: 'Start Date',
        captureddata: 'Captured Data ',
        days: 'days',
        breaksindate: 'Breaks in Date',
        spentsince: 'spent since start of monitoring',
        compareyour: 'Compare your electricity utilisation with others',
        bedsflat: 'Beds flat in England',
        youuse: 'You use 35 % Less electricity than the average 2 bed flat in England',
        patyour: 'Pat your self on the back and have a cup of tea',
        householdin: 'Household in your region',
        youuse1: 'You use 35 % more electricity than the other household in your region',
        whynot: 'Why not check our recommandation for reducing electricity Consumption',
        accountsetup: 'Account details',
        accountnumber: 'Account Number',
        title: 'Title',
        firstname: 'First Name',
        lastname: 'Last Name',
        housename: 'House Name',
        number: 'Number',
        addressline1: 'Address line 1',
        addressline2: 'Address line 2',
        town: 'Town',
        city: 'City',
        zipcode: 'Zip Code',
        country: 'Country',
        emailaddress: 'Email address',
        confirmemailaddress: 'Confirm email address',
        currentusage: 'Current Usage',
        howdoyoucompare: 'How do you compare',
        youbased: 'You (based on your history)',
        other2beds: 'Other 2 bed flats in your neighbourhood',
        yourregion: 'Your region as an average',
        now: 'Now',
        cycle: 'Cycle',
        peak: 'peak',
        offpeak: 'Off Peak',
        saver: 'Saver',
        monitorhistory: 'Monitor history',
        usedsofartoday: 'used since Midnight',
        changeyourpassword: 'Change your password',
        usebelowform: 'Please use the form below to change your password',
        update: 'Update',
        account: 'Account',
        save: 'Save',
        emailforalerts: 'Email for alerts',
        oldpassword: 'Old password',
        newpassword: 'New password',
        confirmnewpassword: 'Confirm new password',
        inyourneighbour: 'in your neighbourhood',
        bed: 'bed',
        other: 'Other'
    })
        //Russian Translation
    .translations('it', {
        Logintext: 'Логин',
        Signuptext: 'Подписаться',
        Logindescription: 'Если у Вас есть Емейл и Пароль, то Вы можете нажать кнопку ниже для перехода к защищенной информации',
        Registrationdescription: 'Чтобы создать Емейл и Пароль, нажмите кнопку ниже и используйте клавиатуру для ввода',
        Email: 'Емейл',
        Password: 'Пароль',
        Rememberme: 'Запомнить',
        Forgotpassword: 'Забыли пароль',
        Register: 'Регистрация',
        Pleasewait: 'Ожидайте',
        Firstname: 'Имя',
        Lastname: 'Фамилия',
        Confirmpassword: 'Подтвердите пароль',
        Submit: 'Отправить',
        Forgotheading: 'Укажите свой Емейл для получения Вашего Пароля',
        Getpassword: 'Получить пароль',
        Menu: 'Меню',
        Hello: 'Добрый день!',
        Utilisationtoday: 'Потребление за день',
        Currentutilisation: 'Текущее потребление',
        Youhaveused: 'Вы использовали',
        Sofartoday: 'на текущий момент',
        Wholehouse: 'Весь дом (квартира)',
        Avgweekdayutilisation: 'Средненедельное потребление',
        Expectedutilisationtoday: 'Ожидаемое потребление за текущий день',
        Setting: 'Установить',
        Signout: 'Выйти',
        Last24hrs: 'Последние 24 часа',
        Last7days: 'Последние 7 дней',
        Lastmonth: 'Последний месяц',
        Last6month: 'Последние 6 месяцев',
        Lastyear: 'Последний год',
        EqualmessageText: 'Среднедневное потребление и ожидаемое потребление за текущий день равны',
        lessmessageText: 'Среднедневное потребление меньше, чем ожидаемое потребление за текущий день',
        greatermessageText: 'Среднедневное потребление выше, чем ожидаемое потребление за текущий день',
        russiantext: 'Русский',
        spanishtext: 'Spanish',
        home: 'Главная',
        household: 'Дом (Квартира)',
        kWh: 'кВт/час',
        browserdetails: 'детали Браузер',
        alerts: 'Предупреждения',
        householdprofile: 'Профиль Дома',
        tariff: 'Тариф',
        setup: 'Расположение',
        propertytype: 'Тип жилья',
        numberofadults: 'Кол-во взрослых',
        numberofchildren: 'Кол-во детей',
        numberofbedroom: 'Кол-во спален',
        electricityprovider: ' Энергопровайдер',
        alertconfiguration: 'Установка Оповещений',
        highUsagehour: 'Высокое потребление - Час',
        highusageday: 'Высокое потребление - День',
        appliancelefton: 'Включенный прибор',
        largeconsumes: 'Большие потребители (напр. Духовка, Обогреватель)',
        computers: 'Компьютеры, ТВ, игры, Консоли и т.п.',
        lights: 'Свет',
        emaildestination: 'Емейл для уведомлений',
        cancel: 'отмена',
        comparisonview: 'Сравнительный анализ',
        type: 'Тип',
        resident: 'Проживающие ',
        adults: 'Взрослые',
        region: 'Область',
        startdate: 'Дата начала',
        captureddata: 'Полученные данные',
        days: 'дни',
        breaksindate: 'Дата окончания',
        spentsince: 'затраты с начала мониторинга',
        compareyour: 'Сравни свое Потребление с другими',
        bedsflat: 'Комнатные квартиры в России',
        youuse: 'Вы тратите на 35% меньше энергии, чем средняя 3-х комн кв-ра в России',
        patyour: 'Откиньтесь назад и выпейте чашку чая',
        householdin: 'Домохозяйство в Вашей области',
        youuse1: 'Вы тратите на 35% больше энергии, чем среднее домохозяйство в Вашей области',
        whynot: 'Проверить наши рекомендации по снижению потребления Энергии',
        accountsetup: 'Установка подробности',
        accountnumber: 'Номер Счета',
        title: 'Префикс',
        firstname: 'Имя',
        lastname: 'Фамилия',
        housename: 'Название дома',
        number: 'Номер дома',
        addressline1: 'Адрес (начало)',
        addressline2: 'Адрес (продолжить)',
        town: 'Поселок',
        city: 'Город',
        zipcode: 'Почтовый индекс',
        country: 'Страна',
        emailaddress: 'Электронная почта',
        confirmemailaddress: 'Подтвердить электронную почту',
        currentusage: 'Текущее Потребление',
        howdoyoucompare: 'Сравнение',
        youbased: 'Вы (основываясь на историч данных)',
        other2beds: 'Другие 3-х комн квартиры рядом',
        yourregion: 'Среднее по области',
        now: 'Сейчас',
        cycle: 'Цикл',
        peak: 'На пике',
        offpeak: 'OffВне пика',
        saver: 'Экономный',
        monitorhistory: 'монитор История',
        usedsofartoday: 'используемые до сих пор сегодня',
        changeyourpassword: 'Изменить пароль',
        usebelowform: 'пожалуйста Используйте форму ниже, чтобы изменить свой пароль',
        update: 'обновление',
        account: 'счет',
        save: 'Сохранить',
        emailforalerts: 'Адрес электронной почты для оповещения',
        oldpassword: 'Старый пароль',
        newpassword: 'Новый пароль',
        confirmnewpassword: 'Подтвердите новый пароль',
        inyourneighbour: 'в вашем районе',
        bed: 'кровать',
        other: 'другой',
    })

    .translations('sp', {
        Logintext: 'Iniciar Sesión',
        Signuptext: 'Contratar',
        Logindescription: 'Si usted tiene correo electrónico y la contraseña , puede utilizar el botón de abajo para acceder al contenido protegido mediante un token',
        Registrationdescription: 'Usa el botón de abajo para crear correo electrónico y contraseña para acceder al contenido protegido mediante un token',
        Email: 'Correo electrónico',
        Password: 'contraseña',
        Rememberme: 'Acuérdate de mí',
        Forgotpassword: 'Has Olvidado Tu Contraseña',
        Register: 'Registrarse',
        Pleasewait: 'por favor espera',
        Firstname: 'Nombre De Pila',
        Lastname: 'apellido',
        Confirmpassword: 'confirmar Contraseña',
        Submit: 'presentar',
        Forgotheading: 'Escriba su E-mail Dirección para recuperar tu contraseña',
        Getpassword: 'Obtener contraseña',
        Menu: 'menú',
        Hello: 'hola',
        Utilisationtoday: 'Utilización Hoy',
        Currentutilisation: 'Utilización actual',
        Youhaveused: 'que ha usado',
        Sofartoday: 'hasta el momento actual',
        Wholehouse: 'Toda la casa',
        Avgweekdayutilisation: 'La utilización media de lunes a viernes',
        Expectedutilisationtoday: 'Utilización prevista hoy',
        Setting: 'ajuste',
        Signout: 'Desconectar',
        Last24hrs: 'últimos 24 horas',
        Last7days: 'últimos 7 días',
        Lastmonth: 'mes pasado',
        Last6month: 'Última 6 meses',
        Lastyear: 'El Año Pasado',
        EqualmessageText: 'Utilización día promedio y la utilización de días previstos son de Igualdad',
        lessmessageText: 'Días de utilización media es inferior a la utilización prevista días',
        greatermessageText: 'Días de utilización media es mayor que la utilización día esperado',
        russiantext: 'Russian',
        spanishtext: 'español',
        home: 'salpicadero',
        household: 'Casa suspenso',
        kWh: 'kWh',
        browserdetails: 'detalles de navegador',
        alerts: 'alertas',
        householdprofile: 'perfil de hogar',
        tariff: 'tarifa',
        setup: 'Preparar',
        propertytype: 'Tipo de Propiedad',
        numberofadults: 'Número de adultos',
        numberofchildren: 'Número de Niños',
        numberofbedroom: 'Número de habitaciones',
        electricityprovider: 'Proveedor de Electricidad',
        alertconfiguration: 'Configuración de alertas',
        highUsagehour: 'Alto Uso - Hora',
        highusageday: 'High Usage - Alto Uso - Día',
        appliancelefton: 'Appliance izquierda en',
        largeconsumes: 'Grandes consume (por ejemplo, horno, calentador)',
        computers: 'Ordenadores, TV, juegos, consolas, etc.',
        lights: 'luces',
        emaildestination: 'email Destino',
        cancel: 'cancelar',
        comparisonview: 'vista de comparación',
        type: 'tipo',
        resident: 'residente ',
        adults: 'adultos',
        region: 'región',
        startdate: 'Fecha De Inicio',
        captureddata: 'Los datos capturados',
        days: 'día',
        breaksindate: 'Las interrupciones de la Fecha',
        spentsince: 'pasado desde el inicio del monitoreo',
        compareyour: 'Compare su utilización de la electricidad con los demás',
        bedsflat: 'Camas Piso en Inglaterra',
        youuse: 'Se utiliza un 35% menos de electricidad que el promedio 2 cama plana en Inglaterra',
        patyour: 'Acaricie a su auto en la parte posterior y tomar una taza de té',
        householdin: 'Se utiliza un 35% más de electricidad que la otra casa en su región',
        youuse1: 'You use 35 % more electricity than the other household in your region',
        whynot: 'Por qué no visitar nuestro Recomendación para la reducción del consumo de electricidad',
        accountsetup: 'Configuración de la cuenta',
        accountnumber: 'Número De Cuenta',
        title: 'título',
        firstname: 'Nombre De Pila',
        lastname: 'apellido',
        housename: 'Nombre Casa',
        number: 'número',
        addressline1: 'Dirección Línea 1',
        addressline2: 'Dirección Línea 2',
        town: 'ciudad',
        city: 'ciudad',
        zipcode: 'Código Postal',
        country: 'país',
        emailaddress: 'Dirección De Correo Electrónico',
        confirmemailaddress: 'Confirmar El Correo',
        currentusage: 'Uso actual',
        howdoyoucompare: '¿Cómo se puede comparar',
        youbased: 'usted (basado en su historial)',
        other2beds: 'Otros 2 cama pisos naborwides',
        yourregion: 'Su región como promedio',
        now: 'ahora',
        cycle: 'ciclo',
        peak: 'pico',
        offpeak: 'fuera de pico',
        saver: 'ahorrador',
        monitorhistory: 'Historia del monitor',
        usedsofartoday: 'utilizado hasta ahora hoy',
        changeyourpassword: 'Cambiar la contraseña',
        usebelowform: 'Por Favor Используйте форму ниже, чтобы изменить свой пароль',
        update: 'actualización',
        account: 'cuenta',
        save: 'Guardar',
        emailforalerts: 'Correo electrónico las alertas',
        oldpassword: 'contraseña anterior',
        newpassword: 'nueva contraseña',
        confirmnewpassword: 'Confirmar nueva contraseña',
        inyourneighbour: 'en su vecindario',
        bed: 'cama',
        other: 'otro',
    });


    $translateProvider.preferredLanguage('en');
});
